---
version: "2.1"
services:
  existing-music-aggregator:
    container_name: mangrana_java_music_aggregator
    image: xeviff/existing-music-aggregator:latest
    build: .
    volumes:
      - ./config:/config
      - ./tokens:/tokens
#    ports:
#      - "8888:8888"